version: "3.5"

services:

  vault0:
    build: ./
    image: local/vault-enterprise
    hostname: vault0
    container_name: vault0
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/vault server -dev -log-level debug -dev-root-token-id password
    ports:
      - "127.0.0.1:8200:8200"
    cap_add:
      - IPC_LOCK

  consul0:
    build: ./
    image: local/consul-enterprise
    hostname: consul0
    container_name: consul0
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -server -log-level debug -ui -config-dir /etc/hashicorp/consul/server -data-dir /var/hashicorp/consul
    ports:
      - "127.0.0.1:8600:8600"
    links:
      - vault0
    volumes:
      - ${PWD}/etc/hashicorp/consul/server/consul.hcl:/etc/hashicorp/consul/server/consul.hcl
      
  consul-client0:
    build: ./
    image: local/consul-enterprise
    hostname: consul-client0
    container_name: consul-client0
    entrypoint: >-
      /usr/local/bin/tini -- /usr/local/bin/consul agent -log-level debug -ui -config-dir /etc/hashicorp/consul/client -data-dir /var/hashicorp/consul
    ports:
      - "127.0.0.1:8500:8500"
    links:
      - consul0
      - vault0
    volumes:
      - ${PWD}/etc/hashicorp/consul/client/consul.hcl:/etc/hashicorp/consul/client/consul.hcl
    
